import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import { Provider } from '@/components/providers';
import { AppContainer } from '@/components/app-container';

import '@/styles/index.css';

const font = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={font.className}>
        <Provider>
          <AppContainer>{children}</AppContainer>
        </Provider>
      </body>
    </html>
  );
}
